/**
 * Webapp Deployment Script
 * Handles building, testing, and deploying web applications
 */

const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const util = require('util');

const execPromise = util.promisify(exec);

class WebappDeployer {
  constructor(config = {}) {
    this.config = {
      buildDir: config.buildDir || 'dist',
      sourceDir: config.sourceDir || 'src',
      environment: config.environment || 'production',
      port: config.port || 3000,
      apiUrl: config.apiUrl || 'http://localhost:3000',
      ...config,
    };
    
    this.steps = [];
    this.errors = [];
  }

  async runCommand(command, description) {
    console.log(`\n📋 ${description}...`);
    try {
      const { stdout, stderr } = await execPromise(command);
      if (stdout) console.log(stdout);
      if (stderr) console.warn(stderr);
      this.steps.push({ step: description, status: 'success' });
      return true;
    } catch (error) {
      console.error(`❌ Error: ${error.message}`);
      this.errors.push({ step: description, error: error.message });
      return false;
    }
  }

  async installDependencies() {
    return this.runCommand('npm install', 'Installing dependencies');
  }

  async runTests() {
    return this.runCommand('npm test', 'Running tests');
  }

  async build() {
    console.log(`\n🔨 Building application for ${this.config.environment} environment...`);
    
    // Create build directory
    if (!fs.existsSync(this.config.buildDir)) {
      fs.mkdirSync(this.config.buildDir, { recursive: true });
    }

    return this.runCommand('npm run build', 'Building application');
  }

  async copyStaticAssets() {
    const publicDir = path.join(this.config.sourceDir, 'public');
    const buildPublic = path.join(this.config.buildDir, 'public');

    if (fs.existsSync(publicDir)) {
      try {
        await execPromise(`cp -r ${publicDir} ${buildPublic}`);
        this.steps.push({ step: 'Copying static assets', status: 'success' });
        return true;
      } catch (error) {
        console.error('Error copying static assets:', error.message);
        this.errors.push({ step: 'Copying static assets', error: error.message });
        return false;
      }
    }
    return true;
  }

  async createEnvFile() {
    const envContent = `NODE_ENV=${this.config.environment}
PORT=${this.config.port}
API_URL=${this.config.apiUrl}
BUILD_TIME=${new Date().toISOString()}`;

    const envPath = path.join(this.config.buildDir, '.env');
    try {
      fs.writeFileSync(envPath, envContent);
      this.steps.push({ step: 'Creating .env file', status: 'success' });
      console.log(`\n✅ Environment file created at ${envPath}`);
      return true;
    } catch (error) {
      console.error('Error creating .env file:', error.message);
      this.errors.push({ step: 'Creating .env file', error: error.message });
      return false;
    }
  }

  async generateDeploymentReport() {
    const reportPath = path.join(this.config.buildDir, 'DEPLOYMENT_REPORT.md');
    const timestamp = new Date().toISOString();
    
    const reportContent = `# Deployment Report

**Deployment Time:** ${timestamp}
**Environment:** ${this.config.environment}
**Port:** ${this.config.port}

## Deployment Steps

${this.steps.map(s => `- ✅ ${s.step}`).join('\n')}

## Build Configuration

- Build Directory: \`${this.config.buildDir}\`
- Source Directory: \`${this.config.sourceDir}\`
- API URL: \`${this.config.apiUrl}\`

${this.errors.length > 0 ? `## Errors\n\n${this.errors.map(e => `- ❌ ${e.step}: ${e.error}`).join('\n')}` : ''}

---
Generated by Webapp Deployer
`;

    try {
      fs.writeFileSync(reportPath, reportContent);
      console.log(`\n📄 Deployment report generated at ${reportPath}`);
      return true;
    } catch (error) {
      console.error('Error generating report:', error.message);
      return false;
    }
  }

  async deploy() {
    console.log('🚀 Starting Webapp Deployment...\n');

    const steps = [
      () => this.installDependencies(),
      () => this.runTests(),
      () => this.build(),
      () => this.copyStaticAssets(),
      () => this.createEnvFile(),
      () => this.generateDeploymentReport(),
    ];

    for (const step of steps) {
      const success = await step();
      if (!success && this.config.stopOnError) {
        console.error('\n❌ Deployment stopped due to error');
        return false;
      }
    }

    if (this.errors.length === 0) {
      console.log('\n✅ Deployment completed successfully!');
      console.log(`📦 Build artifacts are in: ${this.config.buildDir}/`);
      return true;
    } else {
      console.log('\n⚠️ Deployment completed with errors');
      return false;
    }
  }
}

// Export for use as module
module.exports = WebappDeployer;

// Run if executed directly
if (require.main === module) {
  const deployer = new WebappDeployer({
    environment: process.env.NODE_ENV || 'production',
    port: process.env.PORT || 3000,
    apiUrl: process.env.API_URL || 'http://localhost:3000',
  });

  deployer.deploy().then(success => {
    process.exit(success ? 0 : 1);
  });
}
